### PR TITLE
Update GenerateCommand.php

### PR DESCRIPTION
**Pull request by uonick**
array → []
return types added
some syntax fixes

😟

### CODE REVIEW

**Comment by uonick** [comment]
and.. use Laravel [stubs](https://github.com/atehnix/laravel-stubs) for more customizable  class content:
* https://medium.com/@devlob/laravel-crud-generators-614caddf8bea
* https://medium.com/@imfx/create-make-custom-commands-in-laravel-9fa002da582e
* https://stackoverflow.com/questions/34921923/create-an-artisan-command-for-generating-custom-classes-or-files
* https://github.com/laravel/framework/blob/5.2/src/Illuminate/Foundation/Console/ConsoleMakeCommand.php

**Comment by uonick** [comment]
Something like that:

```php
    /**
     * Return file template
     */
    public function getTemplate(): string
    {
        return str_replace(
            [
                '${class}',
            ],
            [
                $this->getInterfaceName(),
            ],
            $this->getStubContents()
        );
    }

    /**
     * Return interface name
     */
    private function getInterfaceName(): string
    {
        return sprintf(
            '%sRepositoryInterface',
            $this->getClassName()
        );
    }


```

```php
    public function getTemplate(): string
    {
        return str_replace(
            [
                '${namespace}',
                '${extends}',
                '${extends_class}',
                '${class}',
                '${constants}',
                '${getters}',
            ],
            [
                $this->getNamespace(),
                $this->getExtends(),
                $this->getExtendsClass(),
                $this->getClassName(),
                $this->getColumns(),
                $this->getGetterMethods(),
            ],
            $this->getStubContents()
        );
    }

```


```php
protected function getStubContents(): string
    {
        return file_get_contents(
            sprintf(
                '%s/%s.stub',
                config('generator.stubs'),
                $this->getType()
            )
        );
    }

```

**Comment by jasonmccreary** [comment]
This looks pretty good. But are you sure that all the of these added return types are supported in PHP 7.0? That's the current supported version in order to remain compatible with Laravel 5.5.

**Comment by uonick** [comment]
Yeah. Return types [appear](https://feryn.eu/blog/php-7-is-now-available-new-features-improvements/) in PHP 7.0

**Comment by jasonmccreary** [comment]
Sure. But not *all* of them. It wasn't [until 7.1](https://www.php.net/manual/en/migration71.new-features.php) `void` and _nullable_ types were supported.

Unfortunately we need to maintain compatibility with 7.0 in order to support the latest Laravel LTS version (5.5).

Feel free to break these up into smaller PRs and we can get the other stuff through, or remove the incompatibilities. 👍

**Pull request closed without merging**
